services:
  palindrome-api:
    image: palindrome-api:0.0.1
    container_name: palindrome-api-1
    build:
      context: ./palindrome-api
    ports:
      - 8080:8080
  word-play-api:
    image: word-play:0.0.1
    container_name: word-play-api-1
    build:
      context: ./word-play-api
    ports:
      - 8081:8080
    environment:
      - PALINDROME_HOST=host.docker.internal
      - PALINDROME_PORT=8080
    depends_on:
      - palindrome-api
