spring:
  application:
    name: movie-api
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      security.protocol: PLAINTEXT
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="user" password="bitnami";
      spring:
        json:
          trusted:
            packages: '*'
    consumer:
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

movie:
  topic: movie-topic
  details:
    topic: movie-details-topic
    group: movie-details-topic-consumer-local
