apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: thursday
  labels:
    app: hello-thursday
  name: hello-thursday
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-thursday
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-thursday
    spec:
      containers:
        - image: irahulsingh/playground:hello-api-1.0.0
          name: hello-thursday
          resources: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wednesday
  labels:
    app: hello
  name: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello
    spec:
      containers:
        - image: irahulsingh/playground:hello-api-1.0.0
          name: hello
          resources: {}
status: {}