spring:
  application:
    name: movie-details-fetcher
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      security.protocol: PLAINTEXT
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="user" password="bitnami";
    consumer:
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

movie:
 topic: movie-topic
 group: movie-topic-consumer-local
 details:
   topic: movie-details-topic

omdb:
  base:
    url: http://www.omdbapi.com/?i=tt3896198&apikey=52d1c7f&t=