spring:
  datasource:
    url: jdbc:mysql://${DB-HOST}:3306/${DB-NAME}
    username: ${DB-USERNAME}
    password: ${DB-PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  cloud:
    azure:
      keyvault:
        secret:
          property-sources:
            - endpoint: https://hl-training.vault.azure.net/
          property-source-enabled: true
#    hibernate:
#      ddl-auto: create
